Gradientbar
AndresFMoya/HTML_and_CSS3-Building_with_Backgrounds_and_Gradients pull request #1
Opened 2019-07-18 20:06 UTC by AndresFMoya

This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of old an old version of the Apple website webpage.

Follow this link to access the website: https://raw.githack.com/AndresFMoya/Building_with_Backgrounds_and_Gradients/gradientbar/index.html

2019-07-19 21:02 UTC, mosaaleb requested changes
## Hi @AndresFMoya

### Good job working in the project :clap:. You have already met most of the requirements, still there some requirements needs to be handled first before moving on. See my comments below.

There's also some redundant `id` selectors in the `nav` section. Let's remove them if they don't serve a purpose.

Please submit a new code review once you met these minor requirements.

Happy coding :computer:

2019-07-19 21:02 UTC, mosaaleb commented on index.html
> +          <img
The images inside `title-images` should be clickable. They are actually links.

2019-07-19 21:02 UTC, mosaaleb commented on index.html
> +          <li class="iphonemodel">
Also images inside `iphonemodels-list` are links.

2019-07-19 21:02 UTC, mosaaleb commented on index.html
> +    <div class="body-container">
The main content should be wrapped around `<main>` tags. You can replace `div.body-container` with `main` to have more semantic tags.

2019-07-23 07:54 UTC, Oghenebrume50 commented
Hi, guys great work, just one requirement left to be met, according to the Microverse requirements, except for the main image, all other images on the site, should be passed as background images, that is the three images that are inscriptions, and the four images that show phone models in the footer should be passed as background images

2019-07-23 07:56 UTC, Oghenebrume50 requested changes

2019-07-23 07:56 UTC, Oghenebrume50 commented on index.html
> +      <div class="iphonemodels-section">
and guys please this should be moved inside the  footer.

2019-07-24 15:28 UTC, AndresFMoya commented
@Oghenebrume50 The images are already set as backgrounds and modified the footer. I'll be pending. Thanks.

2019-07-24 19:29 UTC, mosaaleb commented
reviewing

2019-07-24 19:35 UTC, mosaaleb approved these changes
## Hi @AndresFMoya :wave:

#### Good job :+1:. You can now merge into master

Good luck with the next projects.

#### Happy coding :computer:

2019-07-24 20:59 UTC, merged